### ISSUE TITLE
Visual/Text Tab on WYSIWYG field broken

### ISSUE THREAD

**Issue by jmilne** [elliotcondon/acf#433]
Hi Elliot,

When I try to switch between the Visual/Text tab of the WYSIWYG field it no longer works as expected.

Using Wordpress 4.3 and ACF Pro 5.2.9

**Comment by elliotcondon** [comment]
Hi @jmilne 

Fixed in v5.3.0

**Comment by PSahner** [comment]
Hey Elliot,
issue still exists - using WP 4.3 and ACF Pro 5.3.0
Maybe a helpfull information is that I'm using the WYSIWYG editor inside a flexible content field.

**Comment by elliotcondon** [comment]
HI @PSahner 

Thanks for the info.
I am not able to replicate the issue on my end, can you report any JS errors?

**Comment by PSahner** [comment]
Sadly no - I do not get any errors in console

**Comment by elliotcondon** [comment]
Hi @PSahner 

Can you please contact our support team with login details so we can see the issue on your site?
http://support.advancedcustomfields.com/new-ticket/

**Comment by PSahner** [comment]
Alright, I opened a ticket. Hopefully it's a small fix. We have currently 110 customers using the system.

**Comment by PSahner** [comment]
Just to let you all know - the problem we had was caused by another plugin -> PS Disable Auto Formatting.

**Comment by elliotcondon** [comment]
Thanks
