### ISSUE TITLE
Repeater returns string (which is item count)

### ISSUE THREAD

**Issue by Beee4life** [elliotcondon/acf#620]
If I didn't make a mistake during debugging, I just noticed my repeater function, which is set on an options page, is not working properly anymore. Instead of returning an array with items, it now returns a count of the items in the array.

I had 2 repeaters on [this](http://internationaldownhillfederation.org/the-idf-board/) page, which are entered on an options page. Normally I retrieve the value and loop through the repeater but I get an error now, since you can't loop through a string.

Repeaters (in posts) still return an array.

**Comment by elliotcondon** [comment]
Hi @Beee4life 

Thanks for the bug report, can you please open a support ticket with this same information?
This github repo is not used for support

https://support.advancedcustomfields.com/new-ticket/

Thanks
Elliot

**Comment by Beee4life** [comment]
Done

**Comment by mogmachine** [comment]
Was this fixed, ..what was the support ticket, ..as I still have this issue.

**Comment by elliotcondon** [comment]
Hi @mogmachine 

Support tickets are handled privately between the customer ad our support team. If you have a repeater field that is not returning an array of sub field data, the problem is most likely due to the code used, or a conflict of some sort.

Please open a support ticket to allow our support team to help debug the issue with you:
https://support.advancedcustomfields.com/new-ticket/

Thanks
E

**Comment by Beee4life** [comment]
@mogmachine yes it was fixed, but not by support but by me. There was nog real fix/solution. After emailing back and forth for a while, I created a new repeater field with the same values and used that. Not 1 problem ever since. I never really found out what caused it/what fixed it....

**Comment by MitchEff** [comment]
I realise it's a few years on now, but I'm getting this bug too - it's still present in the most recent version. Zero idea of the cause, but I also had to 'fix' it by deleting the field and creating a new one...

**Comment by cndesign** [comment]
I've developed some pretty complex multisites using ACF and we've run into this issue with repeaters quite a few times.  Never been able to pinpoint what causes it but normally by the time I realize it, it's too late for a delete/recreate or other times the field may have been exported.  Regardless, I've created my own workaround which always seems to work.  Basically, we grab the repeater field value which always returns the number of rows in the repeater, then we cycle through them range() & standard get_post_meta.  Never failed me yet!

$queryID = get_the_ID();
if( get_field('transactions', $queryID) ):
	$numLogs = get_field('transactions', $queryID);		
	foreach (range(0, $numLogs) as $number) {
		$logMeta = 'transactions_' . $number . '_log';
		$valueMeta = 'transactions_' . $number . '_value';
		$log = get_post_meta( $queryID, $logMeta, true );
		$value = get_post_meta( $queryID, $valueMeta, true );
	}
}

Hope it helps someone else!

**Comment by Adrian-Fischer** [comment]
This is an old thread but I think I might have found out the issue (maybe this helps others and the information could be added to the documentation):

Repeater fields (and other special fields) need to be set up properly before using get_field, otherwise they will return string values. In the documentation for adding options pages, the admin_menu hook is mentioned. I made the mistake of not only adding the option pages but also the field groups and fields in this hook. That's why they were not properly initialised when using get_field(). instead field groups and fields must be set up separately in the acf/init hook.
