### ISSUE TITLE
Gutenberg Reusable Blocks and ACF

### ISSUE THREAD

**Issue by lodog23** [elliotcondon/acf#764]
I am not aware if this functionality has been developed yet for ACF beta-4, but I am having a bug where I would create a custom ACF Gutenberg block, I would then insert that block onto a page and turn that custom ACF block into a Reusable block. 

After I do that it adds that block with the content entered into it to the reusable blocks section. I then can insert that reusable block wherever I would like in my site. 

The issue I am running into is when I go to edit the already created reusable block. It allows me to edit the fields, I then click save on the edited reusable block, and update the page, when I refresh the editor page it does not appear to save these changes to that reusable block.

The current work around I have for this is to go to the 'Manage All Reusable Blocks' section and edit the reusable block from there and that seems to work correctly. 

So this appears to only be an issue with saving the updated content for a reusable block when editing it straight in the pages editor. 

Has anyone else experienced this bug?

**Comment by elliotcondon** [comment]
Hi @lodog23 

Thanks for the bug report. I'll add this to our to-do list and will be sure to test shortly.

**Comment by elliotcondon** [comment]
Hi @lodog23 

I've just performed some testing with re-usable blocks but was unable to replicate your exact issue.
I noticed some odd behavior when dealing with two instances of the same re-usable block within the post, but apart from that, everything updated nicely.

If it's not too much to ask, can you please spin up a fresh WP site in "Local by Flywheel" and try to replicate the issue?
Please keep the default theme active and edit the functions.php file with any extra logic needed.​

​​If you can replicate the issue, please export the site (from flywheel app, right click the site and click "export") and attach to your next reply.
​I'll import this and get to work replicating / testing the issue :)

**Comment by lodog23** [comment]
@elliotcondon So I spun up a test site in Local and created a simple block that only has a textarea field. I then can take that block and turn it into a reusable block. I then click edit and edit the content of the block and for me this time it wouldn't even let me edit the textarea field. I also tried taking the reusable block and placing it on another page and after placing it tried to edit the content of the block, but it was grayed out as well for me for this second page. Attached to this reply is my exported copy of my test site.

Thanks for taking a look into this!

[Test Reusable Block.zip](https://github.com/elliotcondon/acf/files/2989121/Test.Reusable.Block.zip)

**Comment by elliotcondon** [comment]
Thanks for the site. I've just imported this and can confirm the issue.

It looks like the "reusable block" is disabling all inputs by default. I'll add this to the to-do list and will find a fix shortly.

**Comment by lodog23** [comment]
@elliotcondon I saw that in the 4.1 update there is a fix for reusable blocks:
* Fixed bug where 'post_types' setting prevents re-usable block edit logic.

I updated ACF to 4.1 and I am able to edit a reusable block, but there are some odd steps I had to take to get there. So I click 'edit' on a reusable block and at first it still keeps the field grayed out. I then have to click below the reusable block where it reads: "Start writing or type / to choose a block". After doing that the grayed out field becomes editable and it seems to save the edited content.

This only works once however. If I don't change any of the content in the field and click 'save', if I click 'edit' again and try to do the trick I mentioned above, it remained grayed out. I did notice though if I click the plus icon to add another block the reusable block field will become editable. 

It seems to me that it won't become editable right away and needs some action to take play to flip the switch to allow it to be. 

A side note I also noticed is if when adding another reusable block right underneath a reusable block they will stack on top of each other until hitting a trigger, like the plus sign icon or clicking to add a paragraph block below.


This was all done on the test site I attached in my previous message.

**Comment by elliotcondon** [comment]
Hi @lodog23 

Thanks again for the info.
The fix in 5.8.0-beta4.1 related the to the "post_types" setting, which is a slightly different issue to this "disabled inputs" problem.

I'll be testing this problem during the week, but it would be great if you can put together some short screen recordings to demonstrate each issue. If you can, please keep the recordings separate for each issue, so I can more easily follow along and tick off the problems as I work.

Thanks again for helping with this. I am confident that we can get the re-usabled blocks problems sorted!

**Comment by lodog23** [comment]
Hi @elliotcondon 

Attached to this message is a screen recording of what I am seeing when using custom ACF blocks as a reusable block. It was hard to isolate the two issues I was having into two separate screen recording because they happen mostly in tandem. So the two issues that are demonstrated in the recording are:

1. When clicking 'Edit' on a reusable block the ACF field will remain grayed out until you hit a trigger event, in my example the plus icon to add a new block. Once the trigger event is hit the field will become editable.

2. It appears that having two reusable blocks one after another on a page and you click edit on the bottom one it appears to stack the two blocks on top of each other until a trigger event happens like mentioned above

Keep up the fantastic work! Appreciate all you do with ACF!

![acf-reusable-block-vid](https://user-images.githubusercontent.com/29789743/54999863-9174e280-4fa7-11e9-98c6-faa0cedd62b8.gif)

**Comment by elliotcondon** [comment]
Hi @lodog23 

Good news. I have been able to fix the reusable blocks issue and will push out a beta5 update later today!

**Comment by ejimford** [comment]
Hello!  I wanted to jump on the coat tails of this thread, since it deals with the same issue I'm facing.  The issue seems to still be happening on Blocks that contain a repeater field.  [Here's a screen recording I did that demonstrates the problem](https://youtu.be/pwL5s7Z3_ss).

I've started a new issue #785 since its for a specific field type.  But feel free to merge these issues.  Thanks!

**Comment by first-wgrt** [comment]
This thread seems to be resolved some time ago, but we are experiencing the exact same problem as described by the OP (so for us, it's not limited to repeater fields). Using ACF PRO 5.8.7 on WP 5.3.

We have a simple block with a wysiwyg field and a link field. It works fine as long as it's not reusable. When I make it reusable, the content of the fields is not saved when I change them; they retain the state they had when I first made the block reusable.

**Comment by ejimford** [comment]
Yeah, @elliotcondon mentioned in #785 (the new issue that I started) that apparently a recent WordPress update broke the fix they had previously implemented.  Its on the to-do list and hopefully we'll see a solution soon, since this definitely hinders the functionality of using ACF for blocks.

**Comment by first-wgrt** [comment]
@ejimford thanks, I overlooked that one.

**Comment by markedwards222** [comment]
it looks like this bug exists again. I've sent a message via your contact form. But I cant edit fields inside reusable blocks. @elliotcondon

**Comment by elliotcondon** [comment]
Hi @markedwards222 

Thanks mate. There are a few problems surrounding ACF Reusable blocks - some of which have been fixed in the 5.9 beta releases. Can you take a short screen recording to demonstrate which issue is affecting you?

**Comment by pandymic** [comment]
Hi @elliotcondon 

Just coming in to say this issue is still present in ACF 5.9. I've put together a short screen-cast outlining this specific use case where I've come across it.

- The block contains a "Repeater" field
- The block is contained inside of a "Group" core block type that is set as a "Reusable Block"
- When editing the block all inputs inside of the Repeater have the "disabled" HTML property
    - "Add More" works and adds new items to the repeater that can be edited
    - "Remove" works and existing items can be removed from the repeater, however...
- Saving has no effect.
    - At first glance the new/updated content is there, however when reloading the page none of the changes within the reusable block have been written to the database.
    - Adding other core blocks (paragraph, etc.) to the reusable field while it is being edited work and they are saved as expected.

I noticed that when the block is in "Edit" mode the input fields are disabled in the main content window, as outlined above.
When the block is in "Preview" mode the ACF form does not appear in the "Block" panel within the right sidebar as it usually does.

https://resources.studiothink.com/misc/acf-gutenberg-reusable-blocks.mp4

**Comment by pandymic** [comment]
I wanted to add that it's possible to modify the content when editing the Reusable block as a post type directly, accessible via:

`/wp-admin/edit.php?post_type=wp_block`

I'm assuming there's simply a gap in logic that allows in-place editing of reusable blocks since they're technically being fed from an outside post type.

**Comment by brizzo** [comment]
I’m experiencing the same issue. Changes made to a reusable ACF block within an existing post do not persist upon block update.

**Comment by plumbweb-thad** [comment]
Same issue for me in 5.9.1.

**Comment by AleksKamb** [comment]
Can confirm problem persists in 5.9.1. 

In my case I get grayed out (disabled) fields in a repeater block inside a block pattern and only new items are editable.
Possible workaround for those using block patterns: Add the pattern, don't save, refresh the page, repeater is magically editable and gets saved as well.

**Comment by elliotcondon** [comment]
Hi @AleksKamb. Thanks for the comment. This "disabled" error is consistent with other reports and findings. We're looking into this along with a bunch of other issues, and will hope to have a solution shortly.

**Comment by anto18-1987** [comment]
Hi @AleksKamb ,
Did we have some solution ,some of the inputs seems disabled when  use reusable block.
![image](https://user-images.githubusercontent.com/74341800/98899898-9b2dbf80-24d6-11eb-8a2a-65be46d9e933.png)

**Comment by hamedJenabi** [comment]
Hi there. any update on this? Still have this problem. 
Thanks
![Screenshot 2021-01-05 at 16 45 02](https://user-images.githubusercontent.com/62768062/103666788-5de52b80-4f75-11eb-89b6-f964c355a26b.png)

**Comment by elliotcondon** [comment]
Hi all. Thanks for keeping this topic alive. 

Yes, we are aware of the issue - it's quite a complicated one to fix. Integrating PHP generated HTML fields into a dynamic React environment is extremely difficult at the best of times, and adding compatibility with the `<disabled />` components is another level of complexity on top.

Please be patient with us, and I hope you are enjoying your well deserved holiday break :)

**Comment by warudin** [comment]
Yikes! Just came across this bug while a client of ours is adding content to their site. What's weird is that I don't see this bug manifesting on my local development environment, but on the online testing environment several fields are disabled.

Is there any news on if and when this problem can be solved?

**Comment by redlumE01** [comment]
Hope this can be fixed.. acf is great, use it on a daily basis and want to use fields in a block pattern.
Having the same issues, all inputs are disabled and not saving

**Comment by Elwood-P** [comment]
Same issue for me. I can't edit repeater fields on a reusable block. Makes a couple of client projects I'm working on quite awkward :/

**Comment by redlumE01** [comment]
Want to bring it back up again.. are there any updates on this? Would be much appreciated :-)

**Comment by funkeeflow** [comment]
Same here! Would be awesome if we get it to work reliable 👍

**Comment by chloewebfx** [comment]
Can't wait until this is fixed! My team solely uses ACF blocks, and we'd love to be able to use reusable blocks, but this bug basically makes it impossible to use them.
