### ISSUE TITLE
Metabox spacing css

### ISSUE THREAD

**Issue by will-b** [elliotcondon/acf#92]
margins on acf_postbox class are not needed / should be a `margin-bottom: 20px`. postbox class has the needed margin bottom.

0 bottom margin does not play well with standard metaboxes.

![metbox class](https://f.cloud.github.com/assets/1074708/753315/b905fd9c-e564-11e2-8e55-4b9ab5ad20e5.png)

**Comment by Volker-E** [comment]
I can confirm this for v. 4.3.9 on WP 4.1

**Comment by elliotcondon** [comment]
Hi @Volker-E 

This should have been fixed for quite some time. Can you you use firebug / inspector to find the rule which is modifying the margin? Perhaps it is not ACF

**Comment by Volker-E** [comment]
Hey @elliotcondon 
You misunderstood my comment, I confirmed that it's fixed.
I did that, because the issue is still marked 'open'. ;)

**Comment by elliotcondon** [comment]
Hi @Volker-E 

Awesome! Thanks for the confirmation, closed! :)
